[package]
name = "fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = { version = "1.4.2", features = ["derive"] }
libfuzzer-sys = "0.4"
cp-library = { path = "../cp-library" }
solutions = { path = "../solutions" }

[[bin]]
name = "smoke"
path = "fuzz_targets/smoke.rs"
test = false
doc = false
bench = false
