[package]
name = "cargo-cp"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Competitive programming workflow helpers"

[dependencies]
anyhow = "1.0"
argh = "0.1"
cargo_metadata = "0.19"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "visit", "visit-mut"] }

[dev-dependencies]
tempfile = "3.14"
